### ISSUE TITLE
Kindly amend READ.me to suggest keeping a Snowflake tab open as a simple alternative

### ISSUE THREAD

**Issue by jlj2** [eyedeekay/blizzard#4]
Kindly amend your READ.me / [introductory page](https://github.com/eyedeekay/blizzard/releases) to suggest a further, simpler alternative besides the four alternatives that you have already listed:

**Keep a Snowflake tab open or pinned.  Slide "Enabled" switch right to turn on:**  
[https://snowflake.torproject.org/embed ](https://snowflake.torproject.org/embed )

NB:  Kindly also address a further issue so that you could advise the countless users of the popular "dark mode" as follows:

**users of a "dark page mode" may need to turn it temporarily off to "light mode" to be able to see the switch.**

The switch may not be visible on that tab as in my case nor on the Firefox (and Chrome?) extensions, and therefore:-
(a) tor end-users do not benefit;  
(b) Snowflake enthusiasts are wasting their time and effort; and
(c) Snowflake enthusiasts might become disillusioned and stop recommending use of Snowflake and even Blizzard when they notice the report that "Number of users your Snowflake has helped circumvent censorship in the last 24 hours" is steadily zero.

Indeed, the Snowflake gitlab will hopefully improve their tab design for dark mode users, but this workaround helps.

Thank you for considering both of these issues to help tor end users more.

**Comment by eyedeekay** [comment]
Having a permanent snowflake tab is not tenable because of the issues with which tabs browsers consider "active." I actually discussed this option with the devs and it's basically and the snowflake website embed is essentially unusable for this reason unless it always stays on the tab the user is viewing, which is the reason why I include it on every single page of my site instead of on just a single page. The much better alternative is the snowflake browser extensions for Firefox and Chrome derived browsers. The dark mode issue is actually with `edgar` my static site generator, so I'll deal with it there.
